version: '3'
services:
    self-prometheus-otel:
        image: prom/prometheus:latest
        container_name: self-prometheus-otel
        ports:
            - '9090:9090'
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
