version: '3'
services:
    self-otel-collector:
        container_name: self-otel-collector
        image: otel/opentelemetry-collector-contrib:latest
        command: ['--config=/etc/otel-collector-config.yaml']
        volumes:
            - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
        ports:
            - '4317:4317' # OTLP gRPC 接口
            - '4318:4318' # OTLP HTTP 接口
            - '9464:9464' # Prometheus exporter 接口

        depends_on:
            - self-loki
            - self-jaeger
            - self-prometheus
        networks:
            - otel-network
    self-loki:
        container_name: self-loki
        image: grafana/loki:latest
        command: -config.file=/etc/loki/local-config.yaml
        volumes:
            - ./config/loki-local-config.yaml:/etc/loki/local-config.yaml
        ports:
            - '3100:3100' # Loki HTTP API 接口
        networks:
            - otel-network

    self-jaeger:
        container_name: self-jaeger
        image: jaegertracing/all-in-one:latest
        environment:
            # - COLLECTOR_ZIPKIN_HTTP_PORT=9411
            - COLLECTOR_OTLP_ENABLED=true
            # - SAMPLING_STRATEGIES_FILE=/etc/jaeger/sampling_strategies.json
        ports:
            - '6831:6831/udp' # UDP port for Jaeger agent
            - '16686:16686' # Web UI
            - '14268:14268' # HTTP port for spans
        networks:
            - otel-network

    self-prometheus:
        image: prom/prometheus:latest
        container_name: self-prometheus
        ports:
            - '9090:9090'
        volumes:
            - ./config/prometheus-local-config.yml:/etc/prometheus/prometheus.yml
        networks:
            - otel-network

    grafana:
        image: grafana/grafana:latest
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
        ports:
            - '3080:3000' # Grafana Web UI
        depends_on:
            - self-loki
            - self-prometheus
            - self-jaeger
        networks:
            - otel-network

networks:
    otel-network:
        driver: bridge
