receivers:
    otlp:
        protocols:
            grpc:
            http:
                endpoint: '0.0.0.0:4318'

exporters:
    loki:
        endpoint: 'http://self-loki:3100/loki/api/v1/push'

service:
    pipelines:
        logs:
            receivers: [otlp]
            exporters: [loki]
