global:
    scrape_interval: 15s # 抓取間隔時間
    evaluation_interval: 15s # 評估間隔時間

scrape_configs:
    - job_name: 'otel-collector'
      scrape_interval: 10s
      static_configs:
          - targets: ['self-otel-collector:9091'] # 指向 OpenTelemetry Collector 的 metrics exporter 端點
