version: '3'
services:
    self-jaeger-otel:
        image: jaegertracing/all-in-one:latest
        container_name: self-jaeger-otel
        environment:
            - COLLECTOR_ZIPKIN_HTTP_PORT=9411
            - COLLECTOR_OTLP_ENABLED=true
            - SAMPLING_STRATEGIES_FILE=/etc/jaeger/sampling_strategies.json
        ports:
            - '14250:14250'
            - '14268:14268'
            - '16686:16686'
            - '4317:4317'
            - '4318:4318'
            - '5775:5775'
            - '5778:5778'
            - '6831:6831'
            - '6832:6832'
            - '9411:9411'
